### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by fopina** [rbw/pysnow#103]
https://github.com/rbw/pysnow/blob/master/pysnow/client.py#L17 why?

This is an important warning to be able to control and pysnow set it to always whenever we import it makes it required to use some weird logic to restore it to whatever setting it was defined previously (in order to be able to control this outside app scope)

**Comment by rbw** [comment]
Good find, thanks. I'll have it removed.

**Comment by rbw** [comment]
Removed in 0.7.6.
Thanks.
