### ISSUE TITLE
Using generator method to stream all records not working on large data sets

### ISSUE THREAD

**Issue by RobinsonCW** [rbw/pysnow#104]
Hi, I don't think this is an issue with the pysnow package per say but was curious if other had encountered this and what if any their workarounds were.

I'm trying to grab all rows and columns from the incident table and dump the data to a csv that I can then load into a Postgres database with a copy from command.  

The error seems to truncate the data so I'm not getting a complete extract.  I have noticed that if I limit the columns it seems to work a little better.  For example, if I extract half of the columns in one run and the other half in another it works fine leading me to think it's something to do with the amount of data and not necessarily the content itself.  Adding a try except block around the writer.writerows line doesn't seem to help isolate the problem either and still results in an incomplete extract.

Does anyone have any ideas around how to correct this ijson issue?

Example Code (1st loop through only)
=========================
        offset = 0
        limit = 10000

        response = incident.get(offset=offset, limit=limit, stream=True)

        # Iterate over the result and write out each row to csv
        with open('servicenow_incidents.csv', 'w', newline='', encoding='utf-8') as mycsv:
            writer = csv.DictWriter(mycsv, fieldnames=fields, dialect='excel', quoting=csv.QUOTE_MINIMAL)
            writer.writeheader()
            writer.writerows(record for record in response.all())

Stacktrace
=======
ijson.backends.python.UnexpectedSymbol: Unexpected symbol ']' at 19253199

**Comment by rbw** [comment]
Hello!

Try increasing the `chunk_size` to a value > 8192.

https://pysnow.readthedocs.io/en/latest/api/resource.html?highlight=chunk_size#pysnow.resource.Resource

**Comment by RobinsonCW** [comment]
Thank you!  I'll keep tinkering with it.  Here's the code change below with the chunk size added to the resource, I'm still seeing the first 10K rows truncated to around ~5-6K records consistently but I'll try different settings and let everyone know if one sticks.  Please let me know if you see anything out of place though.



Code
=====
    
    # Create client object
    c = pysnow.Client(instance='instancename', user=usr, password=pwd)
    c.parameters.exclude_reference_link = True

    # Define a resource, here we'll use the incident table API
    incident = c.resource(chunk_size=81920, api_path='/table/incident')

**Comment by RobinsonCW** [comment]
FYI...throttling the limit back to 1000 in conjunction with the chunk size did the trick.  I was able to get over 350K records exported in under 2 hours.  I'll keep researching the optimal settings for my situation but thanks for the feedback!

**Comment by vijaysatya87** [comment]
Hi Robinson,

Thanks for the information on how to do the pagination. 

Could you please let me know how you are going to the second loop etc until the end to fetch all the records using this pysnow module.

Thanks,
Vijay Sekhar

**Comment by RobinsonCW** [comment]
Hi Vijay,

I'm not sure where I got this idea but it seems to work well for me.

Thanks,
Chance

```
offset = 0
limit = 5000

response = incident.get(
    offset=offset, limit=limit, stream=True, query=qb, fields=fields
)

response_headers = response.headers
total_count = int(response_headers["X-Total-Count"])
loop_iterations = int(total_count / limit)

# print(response.first())

if total_count > 0:
    # Iterate over the result and write out each row to csv
    pass
    
for i in range(loop_iterations):
    print(i)
    offset += limit
    response = incident.get(
        offset=offset, limit=limit, stream=True, query=qb, fields=fields
    )
    pass
```

**Comment by vijaysatya87** [comment]
Hi Robinson,

Thanks for the quick reply. This is really good info.

But, I have observed that this X-Total Count doesn’t show the correct value always, have you also faced this X total Count issue.


Thanks,
Vijay

**Comment by vijaysatya87** [comment]
Hi Chance,

Thanks for providing the looping logic.

I am facing weird issue where I am getting Null sys_id rows (which should not be the case as sys id is a unique not null value), not sure what is causing. Please find below my sample code.
Also, as I said the X-Total Count shows 22159 for my code but the CSV generated only 19160 records. Here, I am querying only for certain groups.

Could you please help me on this issue.

Thanks for your help in advance.

Thanks,
Vijay

```
c.parameters.display_value = True
c.parameters.exclude_reference_link  = True


incident = c.resource(chunk_size=81920, api_path='/table/incident')
print(incident)


qb = (pysnow.QueryBuilder().field('assignment_group.name').equals(assignment_group).AND().field('sys_updated_on').greater_than(last_extract_date))
print(qb)

offset = 0
limit = 3000

response_headers = response.headers
total_count = int(response_headers["X-Total-Count"])
loop_iterations = int(total_count) // limit
print(total_count, loop_iterations)

if total_count > 3000:
	print("Pagination Required")
	pag_flag=1
else:
	print("Pagination not required")
	pag_flag=0

if pag_flag==1:
	for i in range(loop_iterations+1): #Here I added +1 to just to get until the end
		print(i)
		offset += limit
		response = incident.get(offset=offset, limit=limit, query=qb)
		#print(response)
		rows = response.all()
		#print(rows)
		for record in rows:
			df=pd.DataFrame([record])
			df.astype(str).applymap(lambda x: x[:200]).replace('nan', '').to_csv(file, index=False, header=file.tell()==0, mode='a', encoding='UTF-8')
			print(df.head())
else:
	for record in rows:
		df=pd.DataFrame([record])
		df.astype(str).applymap(lambda x: x[:200]).replace('nan', '').to_csv(file, index=False, header=file.tell()==0, mode='a', encoding='UTF-8')
		print(df.head())
print("CSV-Generated")
```

**Comment by vijaysatya87** [comment]
Hi Chance,

Thanks for providing the looping logic.

I am facing weird issue where I am getting Null sys_id rows (which should
not be the case as sys id is a unique not null value), not sure what is
causing. Please find below my sample code.
Also, as I said the X-Total Count shows 22159 for my code but the CSV
generated only 19160 records. Here, I am querying only for certain groups.

Could you please help me on this issue.

Thanks for your help in advance.

Thanks,
Vijay

c.parameters.display_value = True
c.parameters.exclude_reference_link  = True


incident = c.resource(chunk_size=81920, api_path='/table/incident')
print(incident)


qb = (pysnow.QueryBuilder().field('assignment_group.name').equals(assignment_group).AND().field('sys_updated_on').greater_than(last_extract_date))
print(qb)

offset = 0
limit = 3000

response_headers = response.headers
total_count = int(response_headers["X-Total-Count"])
loop_iterations = int(total_count) // limit
print(total_count, loop_iterations)

if total_count > 3000:
	print("Pagination Required")
	pag_flag=1
else:
	print("Pagination not required")
	pag_flag=0

if pag_flag==1:
	for i in range(loop_iterations+1): #Here I added +1 to just to get
until the end
		print(i)
		offset += limit
		response = incident.get(offset=offset, limit=limit, query=qb)
		#print(response)
		rows = response.all()
		#print(rows)
		for record in rows:
			df=pd.DataFrame([record])
			df.astype(str).applymap(lambda x: x[:200]).replace('nan',
'').to_csv(file, index=False, header=file.tell()==0, mode='a',
encoding='UTF-8')
			print(df.head())
else:
	for record in rows:
		df=pd.DataFrame([record])
		df.astype(str).applymap(lambda x: x[:200]).replace('nan',
'').to_csv(file, index=False, header=file.tell()==0, mode='a',
encoding='UTF-8')
		print(df.head())
print("CSV-Generated")

**Comment by RobinsonCW** [comment]
Hi vijaysatya87, haven't had an issues with the X-Total-Count parameters myself.  I've used it to replicate our users table into a database for a year or two now.  The psuedo-code I posted should work for pagination as well, be it for 0, 1 or many iterations.

Thanks,
Chance

**Comment by vijaysatya87** [comment]
Hi Chance,

Thanks. But somehow I am not able to fetch all the records and getting some records with Null Sys_id not sure what is causing the issue.

Anyways, thanks for the help. I will try to debug more and see.

Thanks,
Vijay
