### ISSUE TITLE
Support teamcenter

### ISSUE THREAD

**Issue by GitBib** [rbw/pysnow#108]
How can I get the library to work with teamcenter?

**Comment by rbw** [comment]
I haven't worked with Teamcenter, but I'm guessing it's probably possible.
What are you trying to do exactly?

**Comment by rbw** [comment]
Please re-open or drop me an email if you need help with this.

**Comment by GitBib** [comment]
http://localhost:7001 /tc /table/incident
<pysnow.url_builder.URLBuilder object at 0x03C9F7B0>

Process finished with exit code -1073740791 (0xC0000409)
