### ISSUE TITLE
Paramters - Fields

### ISSUE THREAD

**Issue by bluedottech** [rbw/pysnow#109]
Quick question about sysparm_fields. I'm trying to limit the number of fields in the response with parameters.fields(), but it does not seem to be passing the request properly. I'm still getting back all fields in the custom table. If I submit the same fields using curl, I get only the fields passed back.  

>>> con.parameters.fields
'short_description,account,number'

Is there another method to pass the sysparm_fields list?

Edit: after trying several different things, 2 minutes after posting the question I'm able to run it successfully with .get(query={'query': 'query'}, fields=['short_description', 'number', 'account']).

**Comment by rbw** [comment]
Yep, that's the way to do it.
I realize this isn't included in any of the examples - I'll have that fixed shortly.
