### ISSUE TITLE
Cannot chain `.field()` in QueryBuilder

### ISSUE THREAD

**Issue by infrascripting** [rbw/pysnow#114]
I have the following data structure:

```json
{
    "provided_by": {
        "link": "https://corp.service-now.com/api/now/table/cmdb_ci/3f3db990db3bebc40ecc79bb8c9619f9",
        "value": "3f3db990db3bebc40ecc79bb8c9619f9"
    },
}
```

I'm trying to build a query that finds the object whose `provided_by` has a value for the `value` field. For instance:

```python
provider_val = '3f3db990db3bebc40ecc79bb8c9619f9'
qb = (pysnow.QueryBuilder()
      .field('provided_by').field('value').equals(provider_val)
      )
```

This returns all of the entries without filtering them. I've also tried the following:

```python
provider_val = '3f3db990db3bebc40ecc79bb8c9619f9'
qb = (pysnow.QueryBuilder()
      .field('provided_by').contains(provider_val)
      )
```

This actually returns nothing.

Is there any ways to filter against that `value` key in the `provided_by` field?

**Comment by rbw** [comment]
You can use dot-walking to query by a related table's field.

Try this:
```python
QueryBuilder().field('provided_by.sys_id').equals("3f3db990db3bebc40ecc79bb8c9619f9")
```

**Comment by infrascripting** [comment]
That worked like a charm! Thanks for your explanation.
