### ISSUE TITLE
How to solve pysnow.exceptions.MultipleResults

### ISSUE THREAD

**Issue by aufbakanleitung** [rbw/pysnow#120]
Hi,

I have a PySnow script that searches for users based on their e-mail address:
```python
def get_caller(email):
    incident = c.resource(api_path='/table/sys_user')
    incidents = incident.get(query={"email": email})
    try:
        response = incidents.one()
    except pysnow.exceptions.MultipleResults:
        response = incidents[0]
    except pysnow.exceptions.NoResults:
        response = find_caller_by_old_email(email)
    return response
```

However for some users there are two active records with the same e-mail in the ServiceNow database. 
![two active B-id's](https://user-images.githubusercontent.com/9026889/62296067-accc8e80-b46e-11e9-9fa9-3eea0e0fcc7f.png)

While this is something that shouldn't happen, it's nevertheless something I have to deal with. Else I get the following error:
```terminal
(....)
  File "/Users/hermanvanderveer/anaconda3/lib/python3.6/site-packages/pysnow/response.py", line 45, in __getitem__
    return self.one().get(key)
  File "/Users/hermanvanderveer/anaconda3/lib/python3.6/site-packages/pysnow/response.py", line 213, in one
    raise MultipleResults("Expected single-record result, got multiple")
pysnow.exceptions.MultipleResults: Expected single-record result, got multiple
```

I've tried several options to fix this. `incidents[0]` didn't work, nor did `incidents.first()` which throws an error like `first() only works when stream=true`. 

Also I would prefer if I could get the user with the highest B-number or latest creation date or something. How can I fix this?

**Comment by rbw** [comment]
Try this:

```python
users = c.resource(api_path='/table/sys_user')
result = users.get(query={"email": email}, stream=True).first_or_none()
```

That'd give you the first record (of many, potentially) or None if no matches were found.
Replace `first_or_none()` with `first()` if you want the *NoResults* thrown if there are no matches.

> Also I would prefer if I could get the user with the highest B-number or latest creation date or something. How can I fix this?

Something like this perhaps?:

```python
query = (
    pysnow.QueryBuilder()
    .field("email").equals(email)
    .AND()
    .field("sys_created_on").order_descending()
)
users = c.resource(api_path='/table/sys_user')
result = users.get(query=query, limit=1).one_or_none()  # Use one() to raise NoResults
```

**Comment by aufbakanleitung** [comment]
Thanks! 

That fixed it, and my code is a lot cleaner now ^^
```python
def get_caller(email):
    users = c.resource(api_path='/table/sys_user')
    try:
        result = users.get(query={"email": email}, stream=True).first()
    except pysnow.exceptions.NoResults:
        result = find_caller_by_old_email(email)
    return result

def find_caller_by_old_email(email):
    users = c.resource(api_path='/table/sys_user')
    result = users.get(query={"u_old_email": email}, stream=True).first_or_none()
    return result
```
It seems it automatically picks the newest user already :D
