### ISSUE TITLE
Using ServiceNow Incident Response in an If Statement

### ISSUE THREAD

**Issue by rtirak** [rbw/pysnow#127]
Could someone possibly give me an example of use with an if statement specifically using the assignment_group field? For context here is what I am trying to do:

`incident` = c.resource(api_path='/table/incident')

'#` Query for incidents with state 1
'response = incident.get(query={'number':'INC0454225'})

' #Iterate through response
' for record in response.all():
   '  if (record['assignment_group'] == ' ASSIGNMENT GROUP NAME OR VALUE'):
      '  print('Assignment Group matches')

   ' else:
       ' print('assignment group does not match')

As you can see above I am trying to just compare the assignmnet_group value which when I print the whole incident to the screen teh specific assignment group value looks  like this:

'assignment_group': {   'display_value': 'APPS-Apps TEAM - ITAPPS ''- Service Accounts', 'link': 'https://somecompany.service-now.com/api/now/table/sys_user_group/skdhjghs83kd823jsl3802jjf'},

Can you give me an example or tell me how this should work properly when using pysnow? So that I can compare the assignment group display value == 'SOME GROUP NAME I TYPE IN' and if its true just print to the screen?

**Comment by rbw** [comment]
Hello!

You'll need to set `display_value` to True to resolve relations, such as assignment-group name:

```python
import pysnow

c = pysnow.Client(instance="<instance_name>", user="<username>", password="<password>")
c.parameters.display_value = True

incident = c.resource(api_path="/table/incident")
response = incident.get(query={})

for row in response.all():
    ag = row["assignment_group"]
    if ag and ag["display_value"] == "Service Desk":
        print("{0} belongs to {1}".format(row["number"], ag["display_value"]))

```

**Comment by rbw** [comment]
Closing. Re-open if you still need help with this.
