### ISSUE TITLE
No base exception?

### ISSUE THREAD

**Issue by lingfish** [rbw/pysnow#128]
Hi, any reason why you don't have a base class exception, that everything else in pysnow inherits from?

**Comment by rbw** [comment]
No reason. I think it'd be an easy addition that adds value, that shouldn't cause any breakage.

Something like this perhaps?:
https://github.com/rbw/pysnow/blob/exception-base-type/pysnow/exceptions.py

Or did you have any members in mind?

**Comment by lingfish** [comment]
Yep, nice, that looks great!

**Comment by rbw** [comment]
Fixed in 0.7.11

**Comment by lingfish** [comment]
Thanks!
