### ISSUE TITLE
datetime comparisons don't work

### ISSUE THREAD

**Issue by mvanderlee** [rbw/pysnow#136]
The datetime comparisons result in `opened_at>2019-11-11 00:00:00`. This doesn't actually work. No error is thrown, but ServiceNow ignores the query. 
It should be `opened_at>javascript:gs.dateGenerate("2019-11-11 00:00:00")`

This is implemented in the Criterion handling in PR #135 but not in the QueryBuilder itself.

**Comment by rbw** [comment]
I'm unable to reproduce this; it works without `dateGenerate` on *glide-madrid-12-18-2018__patch7a-10-01-2019_10-03-2019_1530*, at least.

Anyway - I'll have this updated as *GS* seem to be the way to go for dates, and it's already used in `QueryBuilder.between`.

**Comment by rbw** [comment]
@mvanderlee in which version of ServiceNow were you having this issue?

**Comment by rbw** [comment]
Unable to reproduced. Reverted GS code in #138
