### ISSUE TITLE
Date/time comparisons broken for me since #136

### ISSUE THREAD

**Issue by lingfish** [rbw/pysnow#140]
Hi Robert,

I just upgraded to the tag that contains the `gs.dateGenerate` changes (#136), and now my lookups are broken.

I've tested many combinations of `sysparm_display_value`, etc, but what I see is:

* API account is in Australia/Sydney TZ
* Returned dates/times change accordingly based on `sysparm_display_value`
* Your code converts to UTC if a TZ is detected, assuming then that the query wants it in UTC
* Manually querying with Postman, it seems that the date/time sent using `gs.dateGenerate` always results in SN interpreting that as the accounts' TZ, not UTC

So for example, I use a QueryBuilder, using "local" time, and `pysnow` converts that to UTC and I get more results than I should.

I've spent hours scouring SN doco, and haven't found anything definitive around what SN expects in those glide things; even using `sysparm_input_display_value` makes no difference.

Even the doco on `dateGenerate` is vague-ish:

> Generates a date and time for the specified date in GMT.

Yes, so that converts to GMT, but it seems their backend will still search assuming local TZ, or account TZ.

**Comment by lingfish** [comment]
Continuing my rambling, I think what's happening is that `gs.dateGenerate` should be fed dates in the accounts' TZ, and then _it_ converts internally and does it's thing, rather than converting _first_ to UTC, and then feeding that to `gs.dateGenerate`.

**Comment by rbw** [comment]
Thanks for reporting, I'll look into this shortly.

**Comment by rbw** [comment]
Sorry for such a late response.

According to the creator of #136 , datetime comparisons won't work without `dateGenerate`. I wasn't able to reproduce this, but decided to implement it anyway as it did function properly in my (apparently insufficient) tests.

The best way forward is probably to make `dateGenerate` optional in relevant operations. I'll look into this next week.

Again, thanks for reporting and investigating this.

**Comment by rbw** [comment]
This code has now been reverted with #143 and is available in 0.7.14.

Your other points have been noted. Datetime comparison operations will be handled differently in [snowstorm](https://github.com/rbw/snowstorm), a new ServiceNow library I'm working on.
