### ISSUE TITLE
[RFE] simple method to convert record_link into data

### ISSUE THREAD

**Issue by jcpunk** [rbw/pysnow#141]
Lets say I fetch some data from the `incidents` table that looks like:

~~~
'assigned_to': {'link': 'https://dev.service-now.com/api/now/table/sys_user/ce178704f045f400075744d68dcc2b25',
                'value': 'ce178704f045f400075744d68dcc2b25'},
'assignment_group': {'link': 'https://dev.service-now.com/api/now/table/sys_user_group/9cbaff540ada3c590033120149044319',
                     'value': '9cbaff540ada3c590033120149044319'},
~~~

It would be helpful if there was an easy way I could tell `pysnow` "go get this resource.

psudo code:

~~~
RESPONSE = INC_TABLE.get(query={'assignment_group': '9cbaff540ada3c590033120149044319'})
 for ITEM in RESPONSE.all():
   if 'assigned_to' in ITEM:
     print(SNOW_CLIENT.resource(record_link=ITEM['assigned_to']['link']))
~~~

where the `print` there would print out the single record referenced.

**Comment by rbw** [comment]
Hello!

I won't be implementing this in pysnow, this will however be addressed with nested schemas (and field plucking) in [snowstorm](https://github.com/rbw/snowstorm), a new ServiceNow library I'm working on: https://github.com/rbw/snowstorm/issues/3

I'm closing this. Let's continue the discussion there if you want.
