### ISSUE TITLE
Question about ServiceNow Form Action Buttons and Menus

### ISSUE THREAD

**Issue by dfields186** [rbw/pysnow#144]
In our company's implementation of servicenow, there are certain incident tickets which have these "form action buttons" which when you click on them, you are given a menu of various options or actions that you can select.  Here's the element from such an action button:

<button class="form_action_button header  action_context btn btn-default" style="white-space: nowrap" type="submit" value="f364d246db703300c356196c29961913" onclick="var att_action_menu=window.att_action_menu;openAttActionMenuModal();return false;" id="att_action_menu" data-action-name="att_action_menu" gsft_id="f364d246db703300c356196c29961913">AT&amp;T Action Menu</button>

Are these somehow accessible and scriptable using the PySnow APIs or some other API inside of Python?

There is a schema associated with this Action Menu - its called an ActionSchema - partial listing of the schema shown below:

{
	"properties": {
		"action": {
			"type": "string",
			"active": true,
			"label": "Action",
			"help_text": "Select an action",
			"enum": [{
				"label": "Request Escalation",
				"value": "RequestEscalation",
				"help_text": "Request an escalation - Transport tickets ONLY."
			},
			{
				"label": "Ticket Contest",
				"value": "TicketContest",
				"help_text": "Contest a ticket - Transport tickets ONLY."
			},
			{
				"label": "Request To Close",
				"value": "RequestToClose",
				"help_text": "Request ticket closure - Transport tickets ONLY."
			}]
		},
		"action_code": {
			"type": "string",
			"active": true,
			"label": "Action code",
			"help_text": "Select an action code.",
			"dependent_field": "action",
			"enum": [{
				"label": "Service still down",
				"value": "TKTE001",
				"help_text": "",
				"dependent_value": "RequestEscalation"

Any help is so much appreciated!!

Thanks in advance!
David

**Comment by rbw** [comment]
This is a context menu right?
https://docs.servicenow.com/bundle/newyork-platform-user-interface/page/use/using-forms/concept/c_FormContextMenu.html

I don't think these menus can be accessed using the REST API - but I'll investigate this for [snow](https://github.com/rbw/snow), a new ServiceNow library I'm working on.

https://github.com/rbw/snow/issues/12

**Comment by rbw** [comment]
Closing and handling in rbw/snow#12
