### ISSUE TITLE
Problem in calling Service Now with custom end point

### ISSUE THREAD

**Issue by spmurali** [rbw/pysnow#158]
I used pysnow library for integrating applications with Service Now. It worked fantastically in the dev environment with the service now personal developer instance. However in the prod test, my internal service now team have provided client ID, client secret, Resource path and the URL parameters. The resource path is something like "https://xydev.service-now.com/api/eyll2/ansible_integration_services".  In the below code, if I give 'xydev' for the 'instance' parameter, it is taken as eydev.service-now.com. But where can I pass rest of the URL part I,e "api/eyll2/ansible_integration_services" with the URL parameters? I am stuck here. It would be great if I can get some direction here.

s = pysnow.OAuthClient(client_id='437ce7259f5ed81090319fe887dd2871',
                        client_secret='oGS)A(64f~',
                        token_updater=updater, instance='xydev')

**Comment by rbw** [comment]
Looking into this shortly.

**Comment by rbw** [comment]
Sorry for the late response.

You need to create the `Resource` object with a *base_path* and *api_path* when using this API:

```python
...
client.resource(base_path="/api", api_path="/eyll2/ansible_integration_services")
```

This is covered in the documentation.
