### ISSUE TITLE
Host issue

### ISSUE THREAD

**Issue by gogeekness** [rbw/pysnow#159]
### Host issue ### 

Hello.

I am working for a company implement Ansible and we use Service Now.   We are starting out in fetching records through this Python module.  I was wondering about an error as I tested the functionality of tne new Anisble module (snow_record_find).  in Testing I found a error: 
The error was: `requests.exceptions.ConnectionError: host=&apos;ms2dev.osnow.de.service-now.com` 
I never set up the host with `.service-now.com` all I wanted was `ms2dev.osnow.de`.  That is our company domain.

In your code /url_builder.py line 45-46 adds `.service-now.com` to any host.
```
        if instance is not None:
            host = ("%s.service-now.com" % instance).rstrip("/")
```

Is there a way to make this optional a switch or another method?

Thank you,

**Comment by rbw** [comment]
Hello!

The `pysnow.Client` constructor accepts the `host` parameter for this purpose, the Ansible module doesn't seem to support it though.

**Comment by gogeekness** [comment]
Thank you.

Yes I have seen that.  

Sorry to bother.
