### ISSUE TITLE
Why there isn't a context manager in the client?

### ISSUE THREAD

**Issue by DavidMeu** [rbw/pysnow#164]
```
 with Client(..) as servicenow_client:
AttributeError: __enter__
```

**Comment by rbw** [comment]
I think a context manager would be motivated if connections needed to be manually closed, but this is not the case as **pysnow** uses *requests.Session*, which in turn uses urllib3's connection pooling for managing connections.

**Comment by DavidMeu** [comment]
From the docs:
'The Session object allows you to persist certain parameters across requests. It also persists cookies across all requests made from the Session instance, and will use urllib3’s connection pooling. So if you’re making several requests to the same host, the underlying TCP connection will be reused, which can result in a significant performance increase (see HTTP persistent connection).'

Don't see any mention regarding closing connections.
Is it using PoolManager Least Recently Used (LRU) policy for discarding old pools?

**Comment by rbw** [comment]
Good points.

I'll test out your code, add some tests and merge. Thanks :+1:

**Comment by rbw** [comment]
Added with https://github.com/rbw/pysnow/commit/c8ea681e141165b428d8c1917ab186f535f93c8b & pushed to pypi.
