### ISSUE TITLE
Requests Hang with Network Blips

### ISSUE THREAD

**Issue by bendres97** [rbw/pysnow#168]
I've had several instances where my code has completely hung up that I couldn't explain until I was able to backtrack after a known network outage tonight.

I believe that the requests being made to ServiceNow have no timeout, so if at any time a request never gets returned, it just sits there endlessly waiting. 

This has been happening multiple times and I can trace back both tonight's incident (faulty network cable causing outage) and a recent internet outage that I had. Each time, my code was stuck while processing something somewhere. I suspect that all of my other instances of this problem can be attributed to either LAN, WAN, or endpoint failures that requests are unable to recover from.

There is a fix for this since requests, by default, have no timeout:

[https://stackoverflow.com/questions/45267003/python-requests-hanging-freezing](https://stackoverflow.com/questions/45267003/python-requests-hanging-freezing)

I'm opening this Issue in hopes that the developer can make some updates but if I hear nothing back I can take the time to update it myself and submit a pull request.

**Comment by rbw** [comment]
Thanks for reporting and researching the issue.

Do you have any ideas for a good default? I'm thinking around 20-30 seconds would be reasonable.

**Comment by bendres97** [comment]
My thought was more like a minute, just in case somebody is running a large query that the server might need to chew on. The idea is just to keep things from hanging up waiting for a response. I think it would be good to allow the user to specify a different timeout if so desired, just in case they need to run some really large queries. This may even be my case in the future Sent from my Galaxy
-------- Original message --------From: Robert Wikman <notifications@github.com> Date: 3/3/21  17:25  (GMT-06:00) To: rbw/pysnow <pysnow@noreply.github.com> Cc: bendres97 <bendres97@gmail.com>, Author <author@noreply.github.com> Subject: Re: [rbw/pysnow] Requests Hang with Network Blips (#168) 
Thanks for reporting and researching the issue.
Do you have any ideas for a good default? I'm thinking around 20-30 seconds would be reasonable.

**Comment by rbw** [comment]
You're right, a minute is probably more reasonable, although requests yielding a large number of records _should_ be handled via the generator interface (stream=True).

**Comment by rbw** [comment]
Fixed with https://github.com/rbw/pysnow/commit/caad5bf51efe6ab6c868f1f7e6201288a6f4a392
