### ISSUE TITLE
Table API GET pagination support

### ISSUE THREAD

**Issue by siddweiker** [rbw/pysnow#92]
**Feature Request: Table API GET pagination support**

When working with a large set of data, you eventually want to paginate the responses of the REST calls with a limit and offset. This request is to add some additional functionality to to the library to make this easier.

ServiceNow's Table API GET response headers do include a link to the next set of results, in addition the "X-Total-Count" header will contain the amount of rows returned. See https://developer.servicenow.com/app.do#!/rest_api_doc?id=c_TableAPI

Possible ideas include adding a `link_next()` method to the Response class or a `paginate` flag to the Resource object which would then handle all the pagination for you.

For now I am using a generator function (with v0.6.5):
```python
def paginate_get(resource, limit, *args, **kwargs):
    offset = 0
    kwargs['limit'] = limit
    results = list(resource.get(*args, **kwargs).all())

    while len(results) > 0:
        for item in results:
            yield item

        # Increment offset and get the next page
        offset += limit
        results = list(resource.get(*args, **kwargs, offset=offset).all())
```
Used like so:
```python
for record in paginate_get(client.resource(api_path='/table/cmdb_ci_server'), limit=10, query={}):
    print(record)
```

If there is a better way to do this already, I would not mind seeing it and having an example added to the documentation. Thanks.

**Comment by rbw0** [comment]
Hello!

Sorry for such a late response. I've been away on vacation for a couple of weeks.

I'm aware of the link headers exposed by the ServiceNow API, but haven't really found it useful as you can easily control pagination from your client / user agent.
However, I pondered this a little bit after your feature request and realized using link headers for this is much better. I think your suggestion is a good idea and I'll add full support for following link headers in the next release. That is, `Response` methods for `first`, `next`, `prev` and `last`. The 'X-Total-Count' will be exposed as Response.total_count. You'll simply provide a limit and use the pagination methods to change page, with the total number of records always available in `Response`.

Sounds good?

BTW - I noticed you're using `list()` on Response.all(), this is not necessary as of pysnow 0.7, unless you're using the stream parser / generator interface (stream=True to get()). 
Information about this is currently only under "News" in the project's readme, but I'll have this updated in the docs in the next release.

Thanks,
Robert

**Comment by siddweiker** [comment]
I think that sounds great. I am actually still using 0.6.5 so thanks for pointing that out with the list(), I've edited my example with the version for clarity. I look forward to the changes and I hope you had a good vacation. Thanks for all the work on this library!

**Comment by rbw** [comment]
This issue has been open for quite some time now. Really sorry about that.

I've decided not to implement this in current pysnow - instead, this feature will end up in a new,  improved version of this library.

**Comment by vijaysatya87** [comment]
Hi Robert,

Hope you are doing good.

Could you please let me know whether this request has been added in the new version pf pysnow. 
As, I am not able to fetch all the records through pagination, for example X-Total Count shows 22159 but the CSV generated only 19160 records. Here, I am querying only for certain groups.

Could you please help me on this issue.

Thanks for your help in advance.

Thanks,
Vijay Sekhar
