### ISSUE TITLE
Example fetch_one_or_none() fails because

### ISSUE THREAD

**Issue by ghost** [rbw/pysnow#97]
In pysnow 0.7.4 (installed with pip), testing the `fetch_one_or_none()` example locally as read in the [fetching data doc](https://github.com/rbw0/pysnow/blob/master/docs/full_examples/fetch.rst) it fails with:
```
if not self._stream:
>       raise InvalidUsage('first() is only available when stream=True')
E       pysnow.exceptions.InvalidUsage: first() is only available when stream=True
```
It works by adding the param `stream=True` to the line:
`response = incident.get(query={'state': 3}, stream=True)`

By default `stream=False` in the `response.get()` method. Shouldn't it be `True` by default?

**Comment by rbw0** [comment]
Hello! I'll look into this when I'm back from vacation.

**Comment by rbw0** [comment]
>> Shouldn't it be True by default?

Yes, maybe it should. I'm a little split when it comes to this.

The generator interface (stream=True) was the default in versions prior to 0.7.4. I decided to make buffered responses (stream=False) default as the stream parser (generator) introduces some extra complexity and is mostly useful when dealing with large datasets, as it's more memory efficient.

I realize I haven't updated the docs to reflect this change. Sorry about that.

The `Response.first()` method makes sense in a stream context as it only fetches the first bytes of the response. For instance -- your query yields a large number of records, but you're only interested in the first. Using the `first()` method here would fetch the first 8192 bytes (default) of the response when using the stream parser (stream=True), while first() with a buffered response (stream=False) would fetch the entire response, then return index 0.

To demonstrate, using `first()` with stream=True on a response containing 1000 records took about 2 seconds, as opposed to 20 seconds when accessing the first index with stream=False.

I'm considering allowing `first()` with buffered for the sake of consistency, but with a performance warning. Perhaps something like this, if the result contains more than 100 records:
*using first() on a large result set when using buffered responses (stream=False) is discouraged. Consider setting stream=True in get(), or limiting the number of records returned*

That would make the response interface consistent, and make the user aware of the performance implications.

What do you think?

/Robert

**Comment by rbw** [comment]
Closing this.
